//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqPresentation.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinqPresentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2065;257
        ///2115;20
        ///2089;360
        ///2089;359
        ///2009;43
        ///2070;291
        ///2070;290
        ///2175;23
        ///2169;667
        ///2159;627
        ///2130;519
        ///2063;264
        ///2006;28
        ///2126;374
        ///2080;13
        ///2004;18
        ///2052;220
        ///2028;13
        ///2129;514
        ///2034;149
        ///2154;279
        ///2101;409
        ///2074;307
        ///2118;251
        ///2001;5
        ///2204;777
        ///2204;776
        ///2144;73
        ///2137;548
        ///2076;315
        ///2190;734
        ///2014;63
        ///2077;20
        ///2184;712
        ///2026;117
        ///2026;116
        ///2064;267
        ///2055;233
        ///2013;61
        ///2099;400
        ///2079;28
        ///2083;339
        ///2150;139
        ///2146;581
        ///2062;261
        ///2021;28
        ///2149;473
        ///2109;438
        ///2042;179
        ///2205;783
        ///2205;782
        ///2157;620
        ///2148;587
        ///2140;560
        ///2140;559
        ///2024;106
        ///2183;257
        ///2046;197
        ///2002; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string director {
            get {
                return ResourceManager.GetString("director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2065;The Treasure of the Sierra Madre;1948;126;66
        ///2115;Million Dollar Baby;2004;132;116
        ///2089;No Country for Old Men;2007;122;90
        ///2009;Star Wars : Episode V - The Empire Strikes Back;1980;190;10
        ///2070;Singin&apos; in the Rain;1952;103;71
        ///2175;Kill Bill : Vol. 2;2004;136;176
        ///2169;Rocky;1976;119;170
        ///2159;In Bruges;2008;107;160
        ///2130;Stand by Me;1986;89;131
        ///2063;The Third Man;1949;93;64
        ///2006;Schindler&apos;s List;1993;190;7
        ///2126;Gone with the Wind;1939;190;127
        ///2080;Batman Begins;2005;140;81
        ///2004;The Good,the Bad and the Ugl [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string movie {
            get {
                return ResourceManager.GetString("movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 624;Teresa;Wright
        ///712;Francois;Truffaut
        ///198;Ben;Burtt
        ///308;Steve;McQueen
        ///78;Edward;Norton
        ///800;Akihiro;Miwa
        ///785;Tony;Leung Chiu Wai
        ///763;Billy;Crystal
        ///104;Jason;Robards
        ///583;Anouk;Aimee
        ///473;Charles;Laughton
        ///620;William;Wyler
        ///126;Mark;Boone Junior
        ///753;Ben;Gazzara
        ///270;Klaus;Wennemann
        ///268;Jurgen;Prochnow
        ///108;Gabriel;Byrne
        ///326;Lorraine;Gary
        ///764;Mary;Gibbs
        ///748;Richard;Burton
        ///251;Darren;Aronofsky
        ///739;Shigesato;Itoi
        ///557;Dexter;Fletcher
        ///331;Bonnie;Bedelia
        ///691;Don;Taylor
        ///410;John;Cazale
        ///736;Hannah;Gill
        ///257;John;Huston
        ///3 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string people {
            get {
                return ResourceManager.GetString("people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2169;671;Apollo Creed
        ///2169;670;Paulie Pennino
        ///2169;669;Adrian Pennino
        ///2169;668;Rocky Balboa
        ///2006;32;Emilie Schindler
        ///2006;31;Amon Goeth
        ///2006;30;Itzhak Stern
        ///2006;29;Oskar Schindler
        ///2004;22;Aldo Giuffrè
        ///2004;21;Sentenza
        ///2004;20;Blondie
        ///2004;19;Tuco
        ///2052;224;Zeniba
        ///2052;223;Mari Natsuki
        ///2052;222;Miyu Irino
        ///2052;221;Chihiro
        ///2034;152;Pvt. Benjamin Buford &apos;Bubba&apos; Blue
        ///2034;151;Lt. Dan Taylor
        ///2034;150;Jenny Curran
        ///2034;64;Forrest Gump
        ///2154;611;Beulah Bains
        ///2154;279;A Tramp
        ///2154;610;The Kid
        ///2154;609;Edna Purviance [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
    }
}
